/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 27/04/2019 17:10:13
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     180000000
#define MX_PLLQCLKFreq_Value                    180000000
#define MX_PLLRCLKFreq_Value                    180000000
#define MX_PLLSAIPCLKFreq_Value                 48000000
#define MX_PLLSAIQCLKFreq_Value                 96000000
#define MX_PLLI2SPCLKFreq_Value                 48000000
#define MX_PLLI2SQCLKFreq_Value                 48000000
#define MX_PLLI2SRCLKFreq_Value                 48000000
#define MX_SYSCLKFreq_VALUE                     180000000
#define MX_HCLKFreq_Value                       180000000
#define MX_FCLKCortexFreq_Value                 180000000
#define MX_CortexFreq_Value                     180000000
#define MX_AHBFreq_Value                        180000000
#define MX_APB1Freq_Value                       45000000
#define MX_APB2Freq_Value                       90000000
#define MX_APB1TimFreq_Value                    90000000
#define MX_APB2TimFreq_Value                    180000000
#define MX_CECFreq_Value                        32786
#define MX_I2S1Freq_Value                       48000000
#define MX_I2S2Freq_Value                       48000000
#define MX_SAIAFreq_Value                       96000000
#define MX_SAIBFreq_Value                       96000000
#define MX_SDIOFreq_Value                       48000000
#define MX_PWRFreq_Value                        180000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   32000
#define MX_FMPI2C1Freq_Value                    45000000
#define MX_SPDIFRXFreq_Value                    180000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    180000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PC0 */
#define MX_ADCx_IN10_Pin                        PC0
#define MX_ADCx_IN10_GPIOx                      GPIOC
#define MX_ADCx_IN10_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADCx_IN10_GPIO_Pin                   GPIO_PIN_0
#define MX_ADCx_IN10_GPIO_Mode                  GPIO_MODE_ANALOG

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C3       --------------------------------*/

#define MX_I2C3                                 1

/* GPIO Configuration */

/* Pin PC9 */
#define MX_I2C3_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C3_SDA_Pin                         PC9
#define MX_I2C3_SDA_GPIOx                       GPIOC
#define MX_I2C3_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C3_SDA_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C3_SDA_GPIO_AF                     GPIO_AF4_I2C3
#define MX_I2C3_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PA8 */
#define MX_I2C3_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C3_SCL_Pin                         PA8
#define MX_I2C3_SCL_GPIOx                       GPIOA
#define MX_I2C3_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C3_SCL_GPIO_Pin                    GPIO_PIN_8
#define MX_I2C3_SCL_GPIO_AF                     GPIO_AF4_I2C3
#define MX_I2C3_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SPI1       --------------------------------*/

#define MX_SPI1                                 1

/* GPIO Configuration */

/* Pin PA6 */
#define MX_SPI1_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MISO_Pin                        PA6
#define MX_SPI1_MISO_GPIOx                      GPIOA
#define MX_SPI1_MISO_GPIO_PuPd                  GPIO_PULLDOWN
#define MX_SENSOR_MISO                          SPI1_MISO
#define MX_SPI1_MISO_GPIO_Pin                   GPIO_PIN_6
#define MX_SPI1_MISO_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_SPI1_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_MOSI_Pin                        PA7
#define MX_SPI1_MOSI_GPIOx                      GPIOA
#define MX_SPI1_MOSI_GPIO_PuPd                  GPIO_PULLDOWN
#define MX_SENSOR_MOSI                          SPI1_MOSI
#define MX_SPI1_MOSI_GPIO_Pin                   GPIO_PIN_7
#define MX_SPI1_MOSI_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA5 */
#define MX_SPI1_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI1_SCK_Pin                         PA5
#define MX_SPI1_SCK_GPIOx                       GPIOA
#define MX_SPI1_SCK_GPIO_PuPd                   GPIO_PULLUP
#define MX_SENSOR_SCK                           SPI1_SCK
#define MX_SPI1_SCK_GPIO_Pin                    GPIO_PIN_5
#define MX_SPI1_SCK_GPIO_AF                     GPIO_AF5_SPI1
#define MX_SPI1_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PB10 */
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_Pin                         PB10
#define MX_SPI2_SCK_GPIOx                       GPIOB
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_PULLUP
#define MX_DWM1000_SCK                          SPI2_SCK
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_10
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_Pin                        PC1
#define MX_SPI2_MOSI_GPIOx                      GPIOC
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_PULLDOWN
#define MX_DWM1000_MOSI                         SPI2_MOSI
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_1
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF7_SPI2
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC2 */
#define MX_SPI2_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MISO_Pin                        PC2
#define MX_SPI2_MISO_GPIOx                      GPIOC
#define MX_SPI2_MISO_GPIO_PuPd                  GPIO_PULLDOWN
#define MX_DWM1000_MISO                         SPI2_MISO
#define MX_SPI2_MISO_GPIO_Pin                   GPIO_PIN_2
#define MX_SPI2_MISO_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SPI3       --------------------------------*/

#define MX_SPI3                                 1

/* GPIO Configuration */

/* Pin PC10 */
#define MX_SPI3_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_SCK_Pin                         PC10
#define MX_SPI3_SCK_GPIOx                       GPIOC
#define MX_SPI3_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI3_SCK_GPIO_Pin                    GPIO_PIN_10
#define MX_SPI3_SCK_GPIO_AF                     GPIO_AF6_SPI3
#define MX_SPI3_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PA15 */
#define MX_SPI3_NSS_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_NSS_Pin                         PA15
#define MX_SPI3_NSS_GPIOx                       GPIOA
#define MX_SPI3_NSS_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI3_NSS_GPIO_Pin                    GPIO_PIN_15
#define MX_SPI3_NSS_GPIO_AF                     GPIO_AF6_SPI3
#define MX_SPI3_NSS_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB2 */
#define MX_SPI3_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_MOSI_Pin                        PB2
#define MX_SPI3_MOSI_GPIOx                      GPIOB
#define MX_SPI3_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI3_MOSI_GPIO_Pin                   GPIO_PIN_2
#define MX_SPI3_MOSI_GPIO_AF                    GPIO_AF7_SPI3
#define MX_SPI3_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_SPI3_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_MISO_Pin                        PC11
#define MX_SPI3_MISO_GPIOx                      GPIOC
#define MX_SPI3_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI3_MISO_GPIO_Pin                   GPIO_PIN_11
#define MX_SPI3_MISO_GPIO_AF                    GPIO_AF6_SPI3
#define MX_SPI3_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13
#define MX_TMS                                  SYS_JTMS-SWDIO

/* Pin PA14 */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14
#define MX_TCK                                  SYS_JTCK-SWCLK

/* Pin PB3 */
#define MX_SYS_JTDO-SWO_Pin                     PB3
#define MX_SWO                                  SYS_JTDO-SWO

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_S_TIM2_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM2_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH2_Pin                       PA1
#define MX_S_TIM2_CH2_GPIOx                     GPIOA
#define MX_S_TIM2_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM2_CH2_GPIO_Pin                  GPIO_PIN_1
#define MX_S_TIM2_CH2_GPIO_AF                   GPIO_AF1_TIM2

/* Pin PA0-WKUP */
#define MX_S_TIM2_CH1_ETR_GPIO_ModeDefaultPP    GPIO_MODE_AF_PP
#define MX_S_TIM2_CH1_ETR_GPIO_Speed            GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH1_ETR_Pin                   PA0_WKUP
#define MX_S_TIM2_CH1_ETR_GPIOx                 GPIOA
#define MX_S_TIM2_CH1_ETR_GPIO_PuPd             GPIO_NOPULL
#define MX_S_TIM2_CH1_ETR_GPIO_Pin              GPIO_PIN_0
#define MX_S_TIM2_CH1_ETR_GPIO_AF               GPIO_AF1_TIM2

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* Pin PB0 */
#define MX_S_TIM3_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH3_Pin                       PB0
#define MX_S_TIM3_CH3_GPIOx                     GPIOB
#define MX_S_TIM3_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH3_GPIO_Pin                  GPIO_PIN_0
#define MX_S_TIM3_CH3_GPIO_AF                   GPIO_AF2_TIM3

/* Pin PB1 */
#define MX_S_TIM3_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH4_Pin                       PB1
#define MX_S_TIM3_CH4_GPIOx                     GPIOB
#define MX_S_TIM3_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH4_GPIO_Pin                  GPIO_PIN_1
#define MX_S_TIM3_CH4_GPIO_AF                   GPIO_AF2_TIM3

/* Pin PC6 */
#define MX_S_TIM3_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH1_Pin                       PC6
#define MX_S_TIM3_CH1_GPIOx                     GPIOC
#define MX_S_TIM3_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH1_GPIO_Pin                  GPIO_PIN_6
#define MX_S_TIM3_CH1_GPIO_AF                   GPIO_AF2_TIM3

/* Pin PC7 */
#define MX_S_TIM3_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH2_Pin                       PC7
#define MX_S_TIM3_CH2_GPIOx                     GPIOC
#define MX_S_TIM3_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH2_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM3_CH2_GPIO_AF                   GPIO_AF2_TIM3

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* Pin PB9 */
#define MX_S_TIM4_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH4_Pin                       PB9
#define MX_S_TIM4_CH4_GPIOx                     GPIOB
#define MX_S_TIM4_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH4_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM4_CH4_GPIO_AF                   GPIO_AF2_TIM4

/* Pin PB8 */
#define MX_S_TIM4_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH3_Pin                       PB8
#define MX_S_TIM4_CH3_GPIOx                     GPIOB
#define MX_S_TIM4_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH3_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM4_CH3_GPIO_AF                   GPIO_AF2_TIM4

/*-------------------------------- TIM12      --------------------------------*/

#define MX_TIM12                                1

/* GPIO Configuration */

/* Pin PB15 */
#define MX_S_TIM12_CH2_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM12_CH2_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM12_CH2_Pin                      PB15
#define MX_S_TIM12_CH2_GPIOx                    GPIOB
#define MX_S_TIM12_CH2_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM12_CH2_GPIO_Pin                 GPIO_PIN_15
#define MX_S_TIM12_CH2_GPIO_AF                  GPIO_AF9_TIM12

/* Pin PB14 */
#define MX_S_TIM12_CH1_GPIO_ModeDefaultPP       GPIO_MODE_AF_PP
#define MX_S_TIM12_CH1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_S_TIM12_CH1_Pin                      PB14
#define MX_S_TIM12_CH1_GPIOx                    GPIOB
#define MX_S_TIM12_CH1_GPIO_PuPd                GPIO_NOPULL
#define MX_S_TIM12_CH1_GPIO_Pin                 GPIO_PIN_14
#define MX_S_TIM12_CH1_GPIO_AF                  GPIO_AF9_TIM12

/*-------------------------------- UART5      --------------------------------*/

#define MX_UART5                                1

#define MX_UART5_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PD2 */
#define MX_UART5_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART5_RX_Pin                         PD2
#define MX_UART5_RX_GPIOx                       GPIOD
#define MX_UART5_RX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART5_RX_GPIO_Pin                    GPIO_PIN_2
#define MX_UART5_RX_GPIO_AF                     GPIO_AF8_UART5
#define MX_UART5_RX_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_UART5_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART5_TX_Pin                         PC12
#define MX_UART5_TX_GPIOx                       GPIOC
#define MX_UART5_TX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART5_TX_GPIO_Pin                    GPIO_PIN_12
#define MX_UART5_TX_GPIO_AF                     GPIO_AF8_UART5
#define MX_UART5_TX_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA10 */
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1
#define MX_USART1_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART2_TX                            USART2_TX
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA3 */
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART2_RX                            USART2_RX
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- USB_OTG_FS --------------------------------*/

#define MX_USB_OTG_FS                           1

#define MX_USB_OTG_FS_HOST                      1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_OTG_FS_DM_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DM_Pin                    PA11
#define MX_USB_OTG_FS_DM_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DM_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DM_GPIO_Pin               GPIO_PIN_11
#define MX_USB_OTG_FS_DM_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DM_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_USB_OTG_FS_DP_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DP_Pin                    PA12
#define MX_USB_OTG_FS_DP_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DP_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DP_GPIO_Pin               GPIO_PIN_12
#define MX_USB_OTG_FS_DP_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DP_GPIO_Mode              GPIO_MODE_AF_PP

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_PULLUP
#define MX_KEY1                                 PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PC4 */
#define MX_PC4_Pin                              PC4
#define MX_PC4_GPIOx                            GPIOC
#define MX_PC4_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_SPI1_INT                             PC4
#define MX_PC4_GPIO_Pin                         GPIO_PIN_4
#define MX_PC4_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PC3 */
#define MX_PC3_Pin                              PC3
#define MX_PC3_GPIOx                            GPIOC
#define MX_PC3_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_DWM1000_IRQ                          PC3
#define MX_PC3_GPIO_Pin                         GPIO_PIN_3
#define MX_PC3_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PB13 */
#define MX_PB13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB13_Pin                             PB13
#define MX_PB13_GPIOx                           GPIOB
#define MX_PB13_PinState                        GPIO_PIN_SET
#define MX_PB13_GPIO_PuPd                       GPIO_PULLUP
#define MX_SENSOR_NSS3                          PB13
#define MX_PB13_GPIO_Pin                        GPIO_PIN_13
#define MX_PB13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA4 */
#define MX_PA4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA4_Pin                              PA4
#define MX_PA4_GPIOx                            GPIOA
#define MX_PA4_PinState                         GPIO_PIN_SET
#define MX_PA4_GPIO_PuPd                        GPIO_PULLUP
#define MX_SENSOR_NSS                           PA4
#define MX_PA4_GPIO_Pin                         GPIO_PIN_4
#define MX_PA4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_SPI3_INT                             PB5
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PC5 */
#define MX_PC5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC5_Pin                              PC5
#define MX_PC5_GPIOx                            GPIOC
#define MX_PC5_PinState                         GPIO_PIN_SET
#define MX_PC5_GPIO_PuPd                        GPIO_PULLUP
#define MX_SENSOR_NSS2                          PC5
#define MX_PC5_GPIO_Pin                         GPIO_PIN_5
#define MX_PC5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB4 */
#define MX_PB4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_PinState                         GPIO_PIN_SET
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_KEY2                                 PB4
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PC8 */
#define MX_PC8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC8_Pin                              PC8
#define MX_PC8_GPIOx                            GPIOC
#define MX_PC8_PinState                         GPIO_PIN_RESET
#define MX_PC8_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED1                                 PC8
#define MX_PC8_GPIO_Pin                         GPIO_PIN_8
#define MX_PC8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB12 */
#define MX_PB12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB12_Pin                             PB12
#define MX_PB12_GPIOx                           GPIOB
#define MX_PB12_PinState                        GPIO_PIN_SET
#define MX_PB12_GPIO_PuPd                       GPIO_PULLUP
#define MX_DWM1000_CSN                          PB12
#define MX_PB12_GPIO_Pin                        GPIO_PIN_12
#define MX_PB12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

